=== camposer/course_xsl/exercise1/computers.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="computers">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="computer" type="computerType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="computerType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="serial" type="serialType"/>
			<xs:element name="person" type="personType"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required"/>
	</xs:complexType>

	<xs:complexType name="personType">
		<xs:sequence>
			<xs:element name="firstname" type="xs:string"/>
			<xs:element name="lastname" type="xs:string"/>
			<xs:element name="birthDate" type="xs:date"/>
			<xs:element name="height" type="xs:decimal"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required"/>
	</xs:complexType>

	<xs:simpleType name="serialType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{3}"/>
		</xs:restriction>
	</xs:simpleType>


</xs:schema>

=== camposer/course_xsl/exercise1/computers-xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<computers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="computers.xsd">
	<computer id="1">
		<name>uno</name>
		<serial>123</serial>
		<person id="1">
			<firstname>Juan</firstname>
			<lastname>Pérez</lastname>
			<birthDate>1980-01-03</birthDate>
			<height>180</height>		
		</person>
	</computer>
	<computer id="2">
		<name>dos</name>
		<serial>456</serial>
		<person id="2">
			<firstname>María</firstname>
			<lastname>González</lastname>
			<birthDate>1970-04-20</birthDate>
			<height>160</height>
		</person>
	</computer>
	<computer id="3">
		<name>tres</name>
		<serial>789</serial>
		<person id="3">
			<firstname>Pedro</firstname>
			<lastname>García</lastname>
			<birthDate>1971-05-18</birthDate>
			<height>170</height>
		</person>
	</computer>
	<computer id="4">
		<name>cuatro</name>
		<serial>012</serial>
		<person id="1">
			<firstname>Juan</firstname>
			<lastname>Pérez</lastname>
			<birthDate>1980-01-03</birthDate>
			<height>180</height>		
		</person>
	</computer>
</computers>
